# Generated by Django 6.0.6 on 2026-07-06 20:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MigrationRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='running', max_length=16)),
                ('patients_migrated', models.PositiveIntegerField(default=0)),
                ('observations_migrated', models.PositiveIntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fhir_id', models.CharField(db_index=True, max_length=64, unique=True)),
                ('given_name', models.CharField(blank=True, max_length=128)),
                ('family_name', models.CharField(blank=True, max_length=128)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(default='unknown', max_length=16)),
                ('mrn', models.CharField(blank=True, max_length=64)),
                ('source_updated_at', models.DateTimeField(blank=True, null=True)),
                ('migrated_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['family_name', 'given_name'],
            },
        ),
        migrations.CreateModel(
            name='Observation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fhir_id', models.CharField(db_index=True, max_length=64, unique=True)),
                ('code', models.CharField(blank=True, max_length=64)),
                ('display', models.CharField(blank=True, max_length=256)),
                ('value_numeric', models.FloatField(blank=True, null=True)),
                ('value_text', models.CharField(blank=True, max_length=256)),
                ('unit', models.CharField(blank=True, max_length=64)),
                ('status', models.CharField(default='unknown', max_length=32)),
                ('effective_at', models.DateTimeField(blank=True, null=True)),
                ('source_updated_at', models.DateTimeField(blank=True, null=True)),
                ('migrated_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observations', to='migration.patient')),
            ],
            options={
                'ordering': ['-effective_at', 'display'],
            },
        ),
    ]
