# Generated by Django 6.0.6 on 2026-07-06 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('migration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='migrationrun',
            name='pending_batches',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='migrationrun',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
